version: '2'
services:

  redis:
    image: redis:latest
    ports: 
      - 6379:6379

  app-1:
    build: .
    depends_on:
      - redis
    ports:
      - 3000:3000
    environment:
      - PORT=3000

  app-2:
    build: .
    depends_on:
      - redis
    ports:
      - 4000:4000
    environment:
      - PORT=4000