version: '2'
services:

  redis:
    image: redis:latest
    ports: 
      - 6379:6379
    # command: redis-server --save 20 1 --loglevel warning

  # app:
  #   build: .
  #   depends_on:
  #     - redis
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - PORT=3000